<?php
    $tags=[];
    foreach($_POST as $key => $value){
        if(!empty($value)){
            $tags[$key] = $value;
        }else{
            $tags[$key] = "";
        }
    }
    $theme = $tags["couleur"];
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <title>Document</title>
</head>
<body class="<?=$theme?>">
    <header>
        <h1> <?= $tags["nom"] . " " . $tags["prenom"]?></h1>
        <h2>Intitulé du poste</h2>
    </header>
    <main class="cv">
        <section class="cv-infos">
            <h2>Informations</h2>
            <article class="cv-contact">
                <h3>Contact</h3>
                <p class="bold">Email</p>
                <p><?=$tags["email"]?> </p>
                <p class="bold">Téléphone</p>
                <p><?=$tags["tel"]?> </p>
                <p class="bold">Linkedin</p>
                <a href="linkedin.com"><?=$tags["linkedin"]?></a>
                <p class="bold">Github</p>
                <a href="github.com"><?=$tags["github"]?></a>
            </article>
            <article class="cv-bio">
                <h3>Biographie</h3>
                <p><?=$_POST["biographie"]?></p>
            </article>
            <article class="cv-loisirs">
                <ul>
                    <li><?=$tags["loisir1"]?></li>
                    <li><?=$tags["loisir2"]?></li>
                    <li><?=$tags["loisir3"]?></li>
                    <li><?=$tags["loisir4"]?></li>
                </ul>
            </article>
        </section>
        <section class="cv-competences">
            <h2>Compétences</h2>
            <article class="cv-langages">
                <h3>Langages de programmation</h3>
                <ul>
                    <?php
                        foreach($tags["prog"] as $lang){
                            echo "<li> . $lang </li>";
                        }
                    ?>
                </ul>
            </article>
            <article class="cv-frameworks">
                <h3>Frameworks & Librairies</h3>
                <ul>
                    <?php
                        foreach($tags["frameworks"] as $frame){
                            echo "<li> . $frame </li>";
                        }
                    ?>
                </ul>
            </article>
            <article class="cv-logiciels">
                <h3>Logiciels</h3>
                <ul>
                    <?php
                        foreach($tags["logiciels"] as $log){
                            echo "<li> . $log </li>";
                        }
                    ?>
                </ul>
            </article>
            <article class="cv-langues">
                <h3>Langues</h3>
                <ul>
                    <?php
                        foreach($tags["langue"] as $lang){
                            echo "<li> . $lang </li>";
                        }
                    ?>
                </ul>
            </article>
        </section>
    </main>
</body>
</html>