<p>You already have an account ? Please sign in :</p>

<form action="index.php?route=check-connexion" method="post">
    <label for="username">username</label>
    <input type="text" name="username" id="username">
    <label for="password">password</label>
    <input type="password" name="password" id="password">
    <button type="submit">Sign in</button>
</form>

<img src="https://media.vogue.fr/photos/6659f069f3e44a9fa10ea685/16:9/w_5600,h_3150,c_limit/1527411_document_001.jpg" alt="Image des juges de drag race France saison 3" style="width:500px">