<p>You don't have an account ? Please join our extravaganza community:</p>

<form action="index.php?route=check-inscription" method="post">
    <label for="username">username</label>
    <input type="text" name="username" id="username">
    <label for="password">password</label>
    <input type="password" name="password" id="password">
    <label for="email">email</label>
    <input type="email" name="email" id="email">
    <button type="submit">Sign up</button>
</form>

<img src="https://diveng.rosselcdn.net/sites/default/files/dpistyles/diverto_16_9_749w/node_3753/10428/public/thumbnails/image/drag_race_-_s02e01_0.jpg?itok=mKB61Z1t1688460722" alt="Image des queens de drag race france saison 2" style="width:500px">