<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exercice 2 routeur MVC</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li>
                    <a href="index.php">home</a>
                </li>
                <li>
                    <a href="index.php?route=connexion">sign in</a>
                </li>
                <li>
                    <a href="index.php?route=inscription">sign up</a>
                </li>
            </ul>
        </nav>
    </header>
    <?php

    require "templates/$route.phtml";   

    ?>
</body>
</html>