<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <title>Document</title>
</head>
<body>
    <main class="dark">
        <form action="index.php" method="POST">
            <div class="flex">
                <fieldset class="informations">
                    <h1>Informations</h1>
                        <label for="nom">Nom</label>
                        <input type="text" name="nom" id="nom">
                        <label for="prenom">Prénom</label>
                        <input type="text" name="prenom" id="prenom">
                        <label for="email">Email</label>
                        <input type="email" name="email" id="email">
                        <label for="tel">Téléphone</label>
                        <input type="tel" name="tel" id="tel">
                        <label for="linkedin">linkedin</label>
                        <input type="text" name="linkedin" id="linkedin">
                        <label for="github">Github</label>
                        <input type="text" name="github" id="github">
                        <label for="biographie">Biographie</label>
                        <textarea name="biographie" id="biographie"></textarea>
                        <label for="loisir1">Loisir 1</label>
                        <input type="text" name="loisir1" id="loisir1">
                        <label for="loisir2">Loisir 2</label>
                        <input type="text" name="loisir2" id="loisir2">
                        <label for="loisir3">Loisir 3</label>
                        <input type="text" name="loisir3" id="loisir3">
                        <label for="loisir4">Loisir 4</label>
                        <input type="text" name="loisir4" id="loisir4">
                    <h2>Langues</h2>
                        <input type="checkbox" name="langue[]" id="fr" value="Français">
                        <label for="fr">Français</label>
                        <input type="checkbox" name="langue[]" id="en" value="Anglais">
                        <label for="en">Anglais</label>
                        <input type="checkbox" name="langue[]" id="ar" value="Arabe">
                        <label for="ar">Arabe</label>
                        <input type="checkbox" name="langue[]" id="bre" value="Breton">
                        <label for="bre">Breton</label>
                        <input type="checkbox" name="langue[]" id="es" value="Espagnol">
                        <label for="es">Espagnol</label>
                </fieldset>
                <fieldset class="competences">
                    <h1>Compétences</h1>
                        <h2>Langages de programmation</h2>
                            <input type="checkbox" name="prog[]" id="html" value="HTML">
                            <label for="html">HTML</label>
                            <input type="checkbox" name="prog[]" id="css" value="CSS">
                            <label for="css">CSS</label>
                            <input type="checkbox" name="prog[]" id="js" value="javascript">
                            <label for="js">JavaScript</label>
                            <input type="checkbox" name="prog[]" id="php" value="PHP">
                            <label for="php">PHP</label>
                            <input type="checkbox" name="prog[]" id="sql" value="SQL">
                            <label for="sql">SQL</label>
                        <h2>Frameworks et Librairies</h2>
                            <input type="checkbox" name="frameworks[]" id="sass" value="sass">
                            <label for="sass">Sass</label>
                            <input type="checkbox" name="frameworks[]" id="bootstrap" value="bootstrap">
                            <label for="bootstrap">Bootstrap</label>
                            <input type="checkbox" name="frameworks[]" id="symfony" value="symfony">
                            <label for="symfony">Symfony</label>
                            <input type="checkbox" name="frameworks[]" id="laravel" value="laravel">
                            <label for="laravel">Laravel</label>
                        <h2>Logiciels</h2>
                            <input type="checkbox" name="logiciels[]" id="photoshop" value="photoshop">
                            <label for="ps">Photoshop</label>
                            <input type="checkbox" name="logiciels[]" id="illustrator" value="illustrator">
                            <label for="ill">Illustrator</label>
                            <input type="checkbox" name="logiciels[]" id="xd" value="XD">
                            <label for="xd">XD</label>
                            <input type="checkbox" name="logiciels[]" id="figma" value="figma">
                            <label for="figma">Figma</label>
                            <h2>Couleur du CV</h2>
                            <label for="couleur">Couleur</label>
                            <select name="couleur" id="couleur">
                                <option value="dark">Dark</option>
                                <option value="light">Light</option>
                            </select>
                </fieldset>
            </div>
            <button type="submit">Envoyer</button>
        </form>
    </main>
</body>
</html>